//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyllabusAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentStrategie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentStrategie()
        {
            this.CourseAssessmentStrategies = new HashSet<CourseAssessmentStrategie>();
        }
    
        public int AssessmentStrategieId { get; set; }
        public string Strategies { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Program Program { get; set; }
        public virtual University University { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseAssessmentStrategie> CourseAssessmentStrategies { get; set; }
        public virtual Course Course { get; set; }
    }
}
