//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyllabusAutomation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SyllabusAutomationEntities : DbContext
    {
        public SyllabusAutomationEntities()
            : base("name=SyllabusAutomationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssessmentStrategie> AssessmentStrategies { get; set; }
        public virtual DbSet<CIE> CIEs { get; set; }
        public virtual DbSet<CLO> CLOes { get; set; }
        public virtual DbSet<CLOToPLO> CLOToPLOes { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseAssessmentStrategie> CourseAssessmentStrategies { get; set; }
        public virtual DbSet<CourseObjective> CourseObjectives { get; set; }
        public virtual DbSet<CourseType> CourseTypes { get; set; }
        public virtual DbSet<CurriculmnStructure> CurriculmnStructures { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<EduYear> EduYears { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<GenericSkill> GenericSkills { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<LearningPlan> LearningPlans { get; set; }
        public virtual DbSet<LPAssessmentStrategie> LPAssessmentStrategies { get; set; }
        public virtual DbSet<LPCLO> LPCLOes { get; set; }
        public virtual DbSet<LPTeachingStrategie> LPTeachingStrategies { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<MissionOfDepartment> MissionOfDepartments { get; set; }
        public virtual DbSet<MissionOfUniversity> MissionOfUniversities { get; set; }
        public virtual DbSet<PEO> PEOs { get; set; }
        public virtual DbSet<PEOToMission> PEOToMissions { get; set; }
        public virtual DbSet<PEOToPLO> PEOToPLOes { get; set; }
        public virtual DbSet<PLO> PLOes { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<ResourceType> ResourceTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SEE> SEEs { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Syllabu> Syllabus { get; set; }
        public virtual DbSet<TeachingStrategie> TeachingStrategies { get; set; }
        public virtual DbSet<University> Universities { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Week> Weeks { get; set; }
        public virtual DbSet<TeacherDesignation> TeacherDesignations { get; set; }
        public virtual DbSet<TeacherofDept> TeacherofDepts { get; set; }
    }
}
