//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyllabusAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int MarksId { get; set; }
        public Nullable<int> CourseTypeId { get; set; }
        public Nullable<double> CT { get; set; }
        public Nullable<double> Attendence { get; set; }
        public Nullable<double> SEE { get; set; }
        public Nullable<double> SE { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> UniversityId { get; set; }
    
        public virtual CourseType CourseType { get; set; }
        public virtual Department Department { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Program Program { get; set; }
        public virtual University University { get; set; }
    }
}
