//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyllabusAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissionOfUniversity
    {
        public int MissionId { get; set; }
        public string Mission { get; set; }
        public Nullable<int> UniversityId { get; set; }
    
        public virtual University University { get; set; }
    }
}
