//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyllabusAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Syllabu
    {
        public int Id { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> SemesterId { get; set; }
        public string CourseCode { get; set; }
        public Nullable<int> ProgramId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Department Department { get; set; }
        public virtual EduYear EduYear { get; set; }
        public virtual Program Program { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
