//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyllabusAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherofDept
    {
        public int TeacherId { get; set; }
        public string TeacherName { get; set; }
        public string EduDetail { get; set; }
        public string Email { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> DesignationId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual TeacherDesignation TeacherDesignation { get; set; }
    }
}
